<?php

namespace SchemaCraft\QueryBuilder;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;
use SchemaCraft\Generator\Api\ResourceGenerator;
use SchemaCraft\Generator\DependencyResolver;
use SchemaCraft\Scanner\SchemaScanner;
use SchemaCraft\Scanner\TableDefinition;

class QueryCodeWriter
{
    public function __construct(
        private Filesystem $files,
    ) {}

    /**
     * Write a scope method into the model file.
     */
    public function writeScope(QueryDefinition $query, string $scopeCode): WriteResult
    {
        $filePath = $this->resolveFilePath($query->baseModel);

        if (! $this->files->exists($filePath)) {
            return new WriteResult(false, "Model file not found: {$filePath}");
        }

        $content = $this->files->get($filePath);
        $methodName = 'scope'.ucfirst($query->name);

        // Ensure the Builder import exists
        $content = $this->addImportIfMissing($content, 'Illuminate\\Database\\Eloquent\\Builder');

        // Check for existing scope with same name (look for @generated marker)
        $existingPattern = '/\s*\/\*\*\s*\n\s*\*\s*@generated by SchemaCraft Query Builder: '.preg_quote($query->name, '/').'[\s\S]*?public function '.preg_quote($methodName, '/').'[\s\S]*?\n    \}/';

        if (preg_match($existingPattern, $content)) {
            $content = preg_replace($existingPattern, "\n\n".$scopeCode, $content, 1);
        } else {
            // Insert before the closing brace of the class
            $lastBrace = strrpos($content, '}');
            if ($lastBrace === false) {
                return new WriteResult(false, 'Could not find closing brace in model file.');
            }

            $before = rtrim(substr($content, 0, $lastBrace));
            $content = $before."\n\n".$scopeCode."\n}\n";
        }

        $this->files->put($filePath, $content);

        return new WriteResult(true, "Scope {$methodName}() written to model.", $filePath);
    }

    /**
     * Add or update the @method PHPDoc annotation on the model for the scope.
     */
    public function writeScopePhpDoc(QueryDefinition $query, QueryCodeGenerator $generator): WriteResult
    {
        $filePath = $this->resolveFilePath($query->baseModel);

        if (! $this->files->exists($filePath)) {
            return new WriteResult(false, "Model file not found: {$filePath}");
        }

        $content = $this->files->get($filePath);
        $methodLine = $generator->generateScopePhpDocLine($query);

        // Check if @method line for this scope already exists
        $scopeCallName = $query->name;
        $existingPattern = '/\s*\*\s*@method\s+static\s+.*?\b'.preg_quote($scopeCallName, '/').'\b\(.*?\)/';

        if (preg_match($existingPattern, $content)) {
            // Replace existing @method line
            $content = preg_replace($existingPattern, "\n * {$methodLine}", $content, 1);
        } else {
            // Insert into existing docblock or create one
            $content = $this->insertMethodDocLine($content, $methodLine);
        }

        $this->files->put($filePath, $content);

        return new WriteResult(true, '@method PHPDoc added to model.', $filePath);
    }

    /**
     * Write a FormRequest class to disk.
     */
    public function writeFormRequest(QueryDefinition $query, string $code, string $namespace): WriteResult
    {
        $className = ucfirst($query->name).'Request';
        $filePath = $this->resolveFilePath($namespace.'\\'.$className);

        $this->files->ensureDirectoryExists(dirname($filePath));
        $this->files->put($filePath, $code);

        return new WriteResult(true, "{$className} created.", $filePath);
    }

    /**
     * Generate and write a Resource class and all its dependency resources.
     *
     * Uses DependencyResolver to walk the full relationship tree and create
     * any referenced Resource classes that don't already exist on disk.
     *
     * @return array<string, WriteResult> Keyed by resource class name
     */
    public function writeResourceWithDependencies(QueryDefinition $query, string $resourceNamespace, string $modelNamespace): array
    {
        if (! $query->baseSchema || ! class_exists($query->baseSchema)) {
            $resourceClass = $query->modelClass().'Resource';

            return [$resourceClass => new WriteResult(false, "Cannot generate {$resourceClass}: schema class not available.")];
        }

        $table = (new SchemaScanner($query->baseSchema))->scan();
        $results = [];

        // Write the root resource
        $rootResult = $this->writeResourceForTable($table, $resourceNamespace, $modelNamespace);
        $results[$query->modelClass().'Resource'] = $rootResult;

        // Cascade: resolve and write all dependency resources
        $resolver = new DependencyResolver;
        $deps = $resolver->resolveDependencies($table);

        foreach ($deps as $depModelName => $depTable) {
            $depResourceClass = $depModelName.'Resource';
            $results[$depResourceClass] = $this->writeResourceForTable($depTable, $resourceNamespace, $modelNamespace);
        }

        return $results;
    }

    /**
     * Generate and write a single Resource class from a TableDefinition.
     *
     * Skips if the file already exists on disk.
     */
    public function writeResourceForTable(TableDefinition $table, string $resourceNamespace, string $modelNamespace): WriteResult
    {
        $modelName = Str::beforeLast(class_basename($table->schemaClass), 'Schema');
        $resourceClass = $modelName.'Resource';
        $filePath = $this->resolveFilePath($resourceNamespace.'\\'.$resourceClass);

        if ($this->files->exists($filePath)) {
            return new WriteResult(true, "{$resourceClass} already exists.", $filePath);
        }

        $code = (new ResourceGenerator)->generate($table, $resourceNamespace, 'Resource', $modelNamespace);

        $this->files->ensureDirectoryExists(dirname($filePath));
        $this->files->put($filePath, $code);

        return new WriteResult(true, "{$resourceClass} created.", $filePath);
    }

    /**
     * Write a controller method into a controller file (create if needed).
     */
    public function writeControllerMethod(
        QueryDefinition $query,
        string $methodCode,
        string $controllerFqcn,
        string $requestFqcn,
        string $resourceFqcn,
    ): WriteResult {
        $filePath = $this->resolveFilePath($controllerFqcn);
        $controllerClass = class_basename($controllerFqcn);
        $controllerNamespace = Str::beforeLast($controllerFqcn, '\\');

        if (! $this->files->exists($filePath)) {
            // Create a new controller file
            $this->files->ensureDirectoryExists(dirname($filePath));
            $content = $this->buildNewControllerFile(
                $controllerNamespace,
                $controllerClass,
                $requestFqcn,
                $resourceFqcn,
                $query->baseModel,
                $methodCode,
            );
            $this->files->put($filePath, $content);

            return new WriteResult(true, "{$controllerClass} created with {$query->name}() method.", $filePath);
        }

        $content = $this->files->get($filePath);

        // Add use imports if not present
        $content = $this->addImportIfMissing($content, $requestFqcn);
        $content = $this->addImportIfMissing($content, $resourceFqcn);
        $content = $this->addImportIfMissing($content, $query->baseModel);

        // Check for existing method with same @generated marker
        $existingPattern = '/\s*\/\*\*\s*\n\s*\*\s*@generated by SchemaCraft Query Builder: '.preg_quote($query->name, '/').'[\s\S]*?public function '.preg_quote($query->name, '/').'[\s\S]*?\n    \}/';

        if (preg_match($existingPattern, $content)) {
            $content = preg_replace($existingPattern, "\n\n".$methodCode, $content, 1);
        } else {
            // Insert before closing brace
            $lastBrace = strrpos($content, '}');
            if ($lastBrace === false) {
                return new WriteResult(false, 'Could not find closing brace in controller file.');
            }

            $before = rtrim(substr($content, 0, $lastBrace));
            $content = $before."\n\n".$methodCode."\n}\n";
        }

        $this->files->put($filePath, $content);

        return new WriteResult(true, "{$query->name}() method added to {$controllerClass}.", $filePath);
    }

    /**
     * Write a route registration line to the API route file.
     *
     * @param  array{routes: array{file: string, prefix: string, middleware: string[]}}  $apiConfig
     */
    public function writeRouteRegistration(
        QueryDefinition $query,
        string $routeLine,
        string $controllerFqcn,
        array $apiConfig,
    ): WriteResult {
        $routeFile = base_path($apiConfig['routes']['file']);

        if (! $this->files->exists($routeFile)) {
            // Create route file with boilerplate
            $this->files->ensureDirectoryExists(dirname($routeFile));
            $content = "<?php\n\nuse Illuminate\\Support\\Facades\\Route;\nuse {$controllerFqcn};\n\n{$routeLine}\n";
            $this->files->put($routeFile, $content);

            // Register API route file in bootstrap/app.php if not present
            $this->registerApiRouteFile($apiConfig);

            return new WriteResult(true, 'Route file created and route registered.', $routeFile);
        }

        $content = $this->files->get($routeFile);

        // Add controller use import if not present
        $content = $this->addImportIfMissing($content, $controllerFqcn);

        // Check if route for this method already exists
        $methodPattern = preg_quote($query->name, '/');
        if (preg_match("/Route::.+?'".preg_quote($query->name, '/')."'/", $content)) {
            // Replace existing route line
            $content = preg_replace(
                "/.*Route::.+?'".preg_quote($query->name, '/')."'.*\n?/",
                $routeLine."\n",
                $content,
                1,
            );
        } else {
            // Append route line
            $content = rtrim($content)."\n{$routeLine}\n";
        }

        $this->files->put($routeFile, $content);

        return new WriteResult(true, 'Route registered.', $routeFile);
    }

    /**
     * Resolve a FQCN to a file path using PSR-4 conventions.
     */
    public function resolveFilePath(string $fqcn): string
    {
        // App\ namespace → app/
        if (str_starts_with($fqcn, 'App\\')) {
            return app_path(str_replace('\\', '/', substr($fqcn, 4)).'.php');
        }

        // Fallback: assume standard PSR-4 mapping
        return base_path(str_replace('\\', '/', $fqcn).'.php');
    }

    /**
     * Insert a @method doc line into the class docblock, or create one.
     *
     * Finds the chain of docblocks immediately before `class`, takes the first one,
     * and inserts the @method line before its closing tag.
     */
    private function insertMethodDocLine(string $content, string $methodLine): string
    {
        // Match one or more consecutive docblocks followed by the class keyword
        if (preg_match('/(\/\*\*[\s\S]*?\*\/\s*\n)+class\s+/s', $content, $chainMatch, PREG_OFFSET_CAPTURE)) {
            $chainStart = $chainMatch[0][1];
            $chain = $chainMatch[0][0];

            // Find the first docblock's closing */ in the chain
            $firstClose = strpos($chain, ' */');
            if ($firstClose !== false) {
                $newChain = substr($chain, 0, $firstClose)." * {$methodLine}\n */".substr($chain, $firstClose + 3);

                return substr($content, 0, $chainStart).$newChain.substr($content, $chainStart + strlen($chain));
            }
        }

        // No existing docblock — create one before the class keyword
        if (preg_match('/^class\s+\w+/m', $content, $classMatch, PREG_OFFSET_CAPTURE)) {
            $classPos = $classMatch[0][1];
            $docBlock = "/**\n * {$methodLine}\n */\n";

            return substr($content, 0, $classPos).$docBlock.substr($content, $classPos);
        }

        return $content;
    }

    /**
     * Add a use import if it's not already present.
     * Reuses pattern from SchemaWriter::addImport().
     */
    private function addImportIfMissing(string $content, string $import): string
    {
        $escaped = preg_quote($import, '/');

        if (preg_match('/^use\s+\\\\?'.$escaped.'\s*;/m', $content)) {
            return $content;
        }

        $useStatement = "use {$import};";

        if (preg_match_all('/^use\s+.+;$/m', $content, $allMatches, PREG_OFFSET_CAPTURE)) {
            $lastMatch = end($allMatches[0]);
            $lastUseEnd = $lastMatch[1] + strlen($lastMatch[0]);

            return substr($content, 0, $lastUseEnd)."\n".$useStatement.substr($content, $lastUseEnd);
        }

        if (preg_match('/^namespace\s+.+;$/m', $content, $matches, PREG_OFFSET_CAPTURE)) {
            $nsEnd = $matches[0][1] + strlen($matches[0][0]);

            return substr($content, 0, $nsEnd)."\n\n".$useStatement.substr($content, $nsEnd);
        }

        return $content;
    }

    /**
     * Build a new controller file with the initial method.
     */
    private function buildNewControllerFile(
        string $namespace,
        string $className,
        string $requestFqcn,
        string $resourceFqcn,
        string $modelFqcn,
        string $methodCode,
    ): string {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = "namespace {$namespace};";
        $lines[] = '';
        $lines[] = "use {$requestFqcn};";
        $lines[] = "use {$modelFqcn};";
        $lines[] = "use {$resourceFqcn};";
        $lines[] = '';
        $lines[] = "class {$className}";
        $lines[] = '{';
        $lines[] = $methodCode;
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Register the API route file in bootstrap/app.php if not already present.
     *
     * @param  array{routes: array{file: string, prefix: string, middleware: string[]}}  $apiConfig
     */
    private function registerApiRouteFile(array $apiConfig): void
    {
        $bootstrapPath = base_path('bootstrap/app.php');

        if (! $this->files->exists($bootstrapPath)) {
            return;
        }

        $content = $this->files->get($bootstrapPath);
        $routeFile = $apiConfig['routes']['file'];
        $prefix = $apiConfig['routes']['prefix'] ?? 'api';

        // Check if api route is already registered
        if (str_contains($content, 'api:') || str_contains($content, "'api'")) {
            return;
        }

        // Insert api: parameter into withRouting() call
        $content = preg_replace(
            '/(->withRouting\(\s*\n\s*web:\s*.+?,)/',
            "$1\n        api: __DIR__.'/../{$routeFile}',",
            $content,
            1,
        );

        $this->files->put($bootstrapPath, $content);
    }
}
