<?php

namespace SchemaCraft\Tests\Unit;

use PHPUnit\Framework\TestCase;
use SchemaCraft\QueryBuilder\QueryCodeGenerator;
use SchemaCraft\QueryBuilder\QueryDefinition;

class QueryCodeGeneratorTest extends TestCase
{
    private QueryCodeGenerator $generator;

    protected function setUp(): void
    {
        parent::setUp();
        $this->generator = new QueryCodeGenerator;
    }

    // ─── Scope generation ───────────────────────────────────────

    public function test_generates_scope_with_single_hardcoded_condition(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'parameter' => false],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString('public function scopeTestQuery(', $scope);
        $this->assertStringContainsString("->where('posts.status', '=', 'published')", $scope);
    }

    public function test_generates_scope_with_parameterized_condition(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'parameter' => true],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString('?string $status = null', $scope);
        $this->assertStringContainsString('->when($status !== null', $scope);
        $this->assertStringContainsString("'posts.status', '='", $scope);
    }

    public function test_generates_scope_with_inner_join(): void
    {
        $query = $this->queryWith([
            'joins' => [
                ['type' => 'inner', 'table' => 'users', 'localColumn' => 'author_id', 'foreignColumn' => 'id'],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->join('users', 'posts.author_id', '=', 'users.id')", $scope);
    }

    public function test_generates_scope_with_left_join(): void
    {
        $query = $this->queryWith([
            'joins' => [
                ['type' => 'left', 'table' => 'categories', 'localColumn' => 'category_id', 'foreignColumn' => 'id'],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->leftJoin('categories'", $scope);
    }

    public function test_generates_scope_with_right_join(): void
    {
        $query = $this->queryWith([
            'joins' => [
                ['type' => 'right', 'table' => 'tags', 'localColumn' => 'tag_id', 'foreignColumn' => 'id'],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->rightJoin('tags'", $scope);
    }

    public function test_generates_scope_with_selects(): void
    {
        $query = $this->queryWith([
            'selects' => ['posts.*', 'users.name as author_name'],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->select('posts.*', 'users.name as author_name')", $scope);
    }

    public function test_generates_scope_with_order_by(): void
    {
        $query = $this->queryWith([
            'sorts' => [
                ['column' => 'posts.created_at', 'direction' => 'desc'],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->orderBy('posts.created_at', 'desc')", $scope);
    }

    public function test_scope_has_generated_phpdoc(): void
    {
        $query = $this->queryWith([]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString('@generated by SchemaCraft Query Builder: testQuery', $scope);
        $this->assertStringContainsString('Re-generating this query from the visual builder will overwrite this code.', $scope);
    }

    public function test_scope_phpdoc_includes_param_annotations(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'parameter' => true],
                ['column' => 'posts.author_name', 'operator' => 'like', 'parameter' => true],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString('@param  string|null  $status', $scope);
        $this->assertStringContainsString('@param  string|null  $authorName', $scope);
    }

    public function test_generates_scope_with_multiple_joins(): void
    {
        $query = $this->queryWith([
            'joins' => [
                ['type' => 'inner', 'table' => 'users', 'localColumn' => 'author_id', 'foreignColumn' => 'id'],
                ['type' => 'left', 'table' => 'categories', 'localColumn' => 'category_id', 'foreignColumn' => 'id'],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->join('users'", $scope);
        $this->assertStringContainsString("->leftJoin('categories'", $scope);
    }

    public function test_generates_scope_with_mixed_and_or_conditions(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'boolean' => 'and', 'parameter' => false],
                ['column' => 'posts.featured', 'operator' => '=', 'value' => 'true', 'boolean' => 'or', 'parameter' => false],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->where('posts.status'", $scope);
        $this->assertStringContainsString("->orWhere('posts.featured'", $scope);
    }

    public function test_generates_scope_with_is_null_operator(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.deleted_at', 'operator' => 'is_null', 'parameter' => false],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->whereNull('posts.deleted_at')", $scope);
    }

    public function test_generates_scope_with_in_operator(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => 'in', 'value' => ['published', 'draft'], 'parameter' => false],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->whereIn('posts.status', ['published', 'draft'])", $scope);
    }

    public function test_generates_scope_with_like_operator(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.title', 'operator' => 'like', 'value' => '%test%', 'parameter' => false],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->where('posts.title', 'like', '%test%')", $scope);
    }

    // ─── Controller method generation ───────────────────────────

    public function test_generates_controller_method_with_scope(): void
    {
        $query = $this->queryWith([
            'output' => ['scopeOnModel' => true, 'apiEndpoint' => true, 'inlineController' => false],
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'parameter' => true],
            ],
        ]);

        $method = $this->generator->generateControllerMethod($query);

        $this->assertStringContainsString('public function testQuery(TestQueryRequest $request)', $method);
        $this->assertStringContainsString('Post::testQuery(', $method);
        $this->assertStringNotContainsString('Post::query()', $method);
        $this->assertStringContainsString('->paginate($request->per_page ?? 25)', $method);
        $this->assertStringContainsString('PostResource::collection($results)', $method);
    }

    public function test_generates_controller_method_inline(): void
    {
        $query = $this->queryWith([
            'output' => ['scopeOnModel' => false, 'apiEndpoint' => true, 'inlineController' => true],
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'parameter' => true],
            ],
        ]);

        $method = $this->generator->generateControllerMethod($query);

        $this->assertStringContainsString('->when($request->status', $method);
        $this->assertStringNotContainsString('->testQuery(', $method);
    }

    public function test_controller_method_has_generated_phpdoc(): void
    {
        $query = $this->queryWith([]);

        $method = $this->generator->generateControllerMethod($query);

        $this->assertStringContainsString('@generated by SchemaCraft Query Builder: testQuery', $method);
    }

    public function test_inline_controller_with_dynamic_wherehas_captures_request(): void
    {
        $query = $this->queryWith([
            'output' => ['scopeOnModel' => false, 'apiEndpoint' => true, 'inlineController' => true],
            'conditions' => [
                [
                    'type' => 'whereHas',
                    'relationship' => 'tasks',
                    'children' => [
                        ['column' => 'tasks.addressed_at', 'operator' => '>', 'valueType' => 'reference', 'referenceColumn' => 'tasks.due_at'],
                        ['column' => 'tasks.created_at', 'operator' => '<', 'parameter' => true],
                    ],
                ],
            ],
        ]);

        $method = $this->generator->generateControllerMethod($query);

        // Closure should capture $request, not $request->createdAt (which is invalid PHP in use())
        $this->assertStringContainsString('function ($q) use ($request) {', $method);
        $this->assertStringNotContainsString('use ($request->createdAt)', $method);
    }

    // ─── FormRequest generation ─────────────────────────────────

    public function test_generates_form_request_class(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'parameter' => true],
            ],
        ]);

        $request = $this->generator->generateFormRequest($query);

        $this->assertStringContainsString('namespace App\\Http\\Requests;', $request);
        $this->assertStringContainsString('class TestQueryRequest extends FormRequest', $request);
        $this->assertStringContainsString("'status' => 'sometimes|string'", $request);
        $this->assertStringContainsString("'per_page' => 'sometimes|integer|min:1|max:100'", $request);
    }

    public function test_form_request_numeric_rule_for_comparison_operators(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.views', 'operator' => '>', 'parameter' => true],
            ],
        ]);

        $request = $this->generator->generateFormRequest($query);

        $this->assertStringContainsString("'views' => 'sometimes|numeric'", $request);
    }

    public function test_form_request_array_rule_for_in_operator(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => 'in', 'parameter' => true],
            ],
        ]);

        $request = $this->generator->generateFormRequest($query);

        $this->assertStringContainsString("'status' => 'sometimes|array'", $request);
    }

    public function test_form_request_skips_hardcoded_conditions(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'parameter' => false],
                ['column' => 'posts.title', 'operator' => 'like', 'parameter' => true],
            ],
        ]);

        $request = $this->generator->generateFormRequest($query);

        $this->assertStringNotContainsString("'status'", $request);
        $this->assertStringContainsString("'title'", $request);
    }

    public function test_form_request_is_valid_php(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'parameter' => true],
                ['column' => 'posts.views', 'operator' => '>', 'parameter' => true],
            ],
        ]);

        $request = $this->generator->generateFormRequest($query);

        $tmpFile = tempnam(sys_get_temp_dir(), 'qb_req_').'.php';
        file_put_contents($tmpFile, $request);

        exec("php -l {$tmpFile} 2>&1", $lintOutput, $exitCode);
        unlink($tmpFile);

        $this->assertEquals(0, $exitCode, "Generated FormRequest has syntax errors:\n".implode("\n", $lintOutput));
    }

    // ─── Route registration ─────────────────────────────────────

    public function test_generates_route_registration(): void
    {
        $query = $this->queryWith([]);

        $route = $this->generator->generateRouteRegistration($query, 'PostController');

        $this->assertStringContainsString("Route::get('posts/test-query'", $route);
        $this->assertStringContainsString("[PostController::class, 'testQuery']", $route);
    }

    // ─── SQL preview ────────────────────────────────────────────

    public function test_builds_sql_preview_basic(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'parameter' => false],
            ],
            'sorts' => [
                ['column' => 'posts.created_at', 'direction' => 'desc'],
            ],
        ]);

        $sql = $this->generator->buildSqlPreview($query);

        $this->assertStringContainsString('SELECT posts.*', $sql);
        $this->assertStringContainsString('FROM posts', $sql);
        $this->assertStringContainsString("WHERE posts.status = 'published'", $sql);
        $this->assertStringContainsString('ORDER BY posts.created_at DESC', $sql);
    }

    public function test_builds_sql_preview_with_join(): void
    {
        $query = $this->queryWith([
            'joins' => [
                ['type' => 'inner', 'table' => 'users', 'localColumn' => 'author_id', 'foreignColumn' => 'id'],
            ],
        ]);

        $sql = $this->generator->buildSqlPreview($query);

        $this->assertStringContainsString('INNER JOIN users ON posts.author_id = users.id', $sql);
    }

    public function test_builds_sql_preview_with_parameter_placeholder(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'parameter' => true],
            ],
        ]);

        $sql = $this->generator->buildSqlPreview($query);

        $this->assertStringContainsString('posts.status = :status', $sql);
    }

    public function test_builds_sql_preview_with_custom_selects(): void
    {
        $query = $this->queryWith([
            'selects' => ['posts.id', 'posts.title', 'users.name as author_name'],
        ]);

        $sql = $this->generator->buildSqlPreview($query);

        $this->assertStringContainsString('SELECT posts.id, posts.title, users.name as author_name', $sql);
    }

    // ─── Grouped conditions ────────────────────────────────────────

    public function test_generates_scope_with_grouped_conditions(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'parameter' => false],
                ['column' => 'posts.title', 'operator' => 'like', 'parameter' => true, 'groupId' => 1],
                ['column' => 'posts.body', 'operator' => 'like', 'parameter' => true, 'groupId' => 1],
            ],
            'conditionGroups' => [
                ['id' => 1, 'boolean' => 'or', 'parentGroupId' => null],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->where('posts.status', '=', 'published')", $scope);
        $this->assertStringContainsString('->orWhere(function ($q) use ($title, $body) {', $scope);
        $this->assertStringContainsString('$q->when($title', $scope);
        $this->assertStringContainsString('$q->when($body', $scope);
    }

    public function test_generates_scope_with_nested_groups(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'parameter' => false],
                ['column' => 'posts.title', 'operator' => 'like', 'parameter' => true, 'groupId' => 1],
                ['column' => 'posts.slug', 'operator' => 'like', 'parameter' => true, 'groupId' => 2],
            ],
            'conditionGroups' => [
                ['id' => 1, 'boolean' => 'or', 'parentGroupId' => null],
                ['id' => 2, 'boolean' => 'and', 'parentGroupId' => 1],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString('->orWhere(function ($q) use ($title, $slug) {', $scope);
        $this->assertStringContainsString('->where(function ($q) use ($slug) {', $scope);
    }

    public function test_sql_preview_with_grouped_conditions(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'parameter' => false],
                ['column' => 'posts.title', 'operator' => 'like', 'parameter' => true, 'groupId' => 1],
                ['column' => 'posts.body', 'operator' => 'like', 'parameter' => true, 'groupId' => 1],
            ],
            'conditionGroups' => [
                ['id' => 1, 'boolean' => 'or', 'parentGroupId' => null],
            ],
        ]);

        $sql = $this->generator->buildSqlPreview($query);

        $this->assertStringContainsString("posts.status = 'published'", $sql);
        $this->assertStringContainsString('OR (', $sql);
        $this->assertStringContainsString('posts.title LIKE :title', $sql);
        $this->assertStringContainsString('posts.body LIKE :body', $sql);
    }

    public function test_parameterized_conditions_include_grouped(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'parameter' => false],
                ['column' => 'posts.title', 'operator' => 'like', 'parameter' => true, 'groupId' => 1],
            ],
            'conditionGroups' => [
                ['id' => 1, 'boolean' => 'or', 'parentGroupId' => null],
            ],
        ]);

        $params = $query->parameterizedConditions();
        $this->assertCount(1, $params);
        $this->assertEquals('posts.title', $params[0]->column);
    }

    // ─── Column reference conditions ───────────────────────────────

    public function test_generates_scope_with_column_reference(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'tasks.completed_at', 'operator' => '>=', 'valueType' => 'reference', 'referenceColumn' => 'tasks.due_at'],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->whereColumn('tasks.completed_at', '>=', 'tasks.due_at')", $scope);
        $this->assertStringNotContainsString('$completedAt', $scope);
    }

    public function test_generates_scope_with_or_column_reference(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'tasks.completed_at', 'operator' => '>=', 'boolean' => 'or', 'valueType' => 'reference', 'referenceColumn' => 'tasks.due_at'],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->orWhereColumn('tasks.completed_at', '>=', 'tasks.due_at')", $scope);
    }

    public function test_sql_preview_with_column_reference(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'tasks.completed_at', 'operator' => '>=', 'valueType' => 'reference', 'referenceColumn' => 'tasks.due_at'],
            ],
        ]);

        $sql = $this->generator->buildSqlPreview($query);

        $this->assertStringContainsString('tasks.completed_at >= tasks.due_at', $sql);
        $this->assertStringNotContainsString("'tasks.due_at'", $sql);
    }

    public function test_generates_scope_with_mixed_value_types(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'valueType' => 'hardcoded'],
                ['column' => 'posts.title', 'operator' => 'like', 'valueType' => 'dynamic'],
                ['column' => 'posts.updated_at', 'operator' => '>', 'valueType' => 'reference', 'referenceColumn' => 'posts.created_at'],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->where('posts.status', '=', 'published')", $scope);
        $this->assertStringContainsString('->when($title !== null', $scope);
        $this->assertStringContainsString("->whereColumn('posts.updated_at', '>', 'posts.created_at')", $scope);
    }

    public function test_generates_scope_with_column_reference_in_group(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'tasks.completed_at', 'operator' => '>=', 'valueType' => 'reference', 'referenceColumn' => 'tasks.due_at', 'groupId' => 1],
            ],
            'conditionGroups' => [
                ['id' => 1, 'boolean' => 'and', 'parentGroupId' => null],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString('->where(function ($q) {', $scope);
        $this->assertStringContainsString("\$q->whereColumn('tasks.completed_at', '>=', 'tasks.due_at')", $scope);
    }

    public function test_form_request_skips_reference_conditions(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.title', 'operator' => 'like', 'valueType' => 'dynamic'],
                ['column' => 'posts.updated_at', 'operator' => '>', 'valueType' => 'reference', 'referenceColumn' => 'posts.created_at'],
            ],
        ]);

        $request = $this->generator->generateFormRequest($query);

        $this->assertStringContainsString("'title'", $request);
        $this->assertStringNotContainsString("'updatedAt'", $request);
    }

    public function test_scope_parameters_skip_reference_conditions(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.title', 'operator' => 'like', 'valueType' => 'dynamic'],
                ['column' => 'posts.updated_at', 'operator' => '>', 'valueType' => 'reference', 'referenceColumn' => 'posts.created_at'],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString('?string $title = null', $scope);
        $this->assertStringNotContainsString('$updatedAt', $scope);
    }

    // ─── whereHas code generation ────────────────────────────────

    public function test_generates_scope_with_simple_has(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'boolean' => 'and',
                    'hasType' => 'has',
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->has('comments')", $scope);
    }

    public function test_generates_scope_with_doesnt_have(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'doesntHave',
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->whereDoesntHave('comments'", $scope);
    }

    public function test_generates_scope_with_has_count_constraint(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'has',
                    'countOperator' => '>=',
                    'countValue' => 5,
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->has('comments', '>=', 5)", $scope);
    }

    public function test_generates_scope_with_where_has_and_conditions(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'boolean' => 'and',
                    'hasType' => 'has',
                    'conditions' => [
                        ['column' => 'comments.approved', 'operator' => '=', 'value' => '1', 'valueType' => 'hardcoded'],
                    ],
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->whereHas('comments', function (\$q) {", $scope);
        $this->assertStringContainsString("\$q->where('comments.approved', '=', 1)", $scope);
        $this->assertStringContainsString('})', $scope);
    }

    public function test_generates_scope_with_where_has_conditions_and_count(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'has',
                    'countOperator' => '>=',
                    'countValue' => 3,
                    'conditions' => [
                        ['column' => 'comments.approved', 'operator' => '=', 'value' => '1', 'valueType' => 'hardcoded'],
                    ],
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->whereHas('comments', function (\$q) {", $scope);
        $this->assertStringContainsString("\$q->where('comments.approved', '=', 1)", $scope);
        $this->assertStringContainsString("}, '>=', 3)", $scope);
    }

    public function test_generates_scope_with_or_where_has(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'boolean' => 'or',
                    'hasType' => 'has',
                    'conditions' => [
                        ['column' => 'comments.approved', 'operator' => '=', 'value' => '1', 'valueType' => 'hardcoded'],
                    ],
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->orWhereHas('comments', function (\$q) {", $scope);
    }

    public function test_generates_scope_with_where_doesnt_have_conditions(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'doesntHave',
                    'conditions' => [
                        ['column' => 'comments.spam', 'operator' => '=', 'value' => '1', 'valueType' => 'hardcoded'],
                    ],
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->whereDoesntHave('comments', function (\$q) {", $scope);
        $this->assertStringContainsString("\$q->where('comments.spam', '=', 1)", $scope);
    }

    public function test_generates_scope_with_where_has_dynamic_condition(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'has',
                    'conditions' => [
                        ['column' => 'comments.author_name', 'operator' => 'like', 'valueType' => 'dynamic'],
                    ],
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->whereHas('comments', function (\$q) use (\$authorName) {", $scope);
        $this->assertStringContainsString('$q->when($authorName', $scope);
    }

    public function test_sql_preview_with_where_has(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'has',
                    'conditions' => [
                        ['column' => 'comments.approved', 'operator' => '=', 'value' => '1', 'valueType' => 'hardcoded'],
                    ],
                ],
            ],
        ]);

        $sql = $this->generator->buildSqlPreview($query);

        $this->assertStringContainsString('EXISTS (SELECT * FROM comments', $sql);
        $this->assertStringContainsString("comments.approved = '1'", $sql);
    }

    public function test_sql_preview_with_doesnt_have(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'doesntHave',
                ],
            ],
        ]);

        $sql = $this->generator->buildSqlPreview($query);

        $this->assertStringContainsString('NOT EXISTS (SELECT * FROM comments)', $sql);
    }

    public function test_sql_preview_with_where_has_count_constraint(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'has',
                    'countOperator' => '>=',
                    'countValue' => 5,
                ],
            ],
        ]);

        $sql = $this->generator->buildSqlPreview($query);

        $this->assertStringContainsString('EXISTS (SELECT * FROM comments)', $sql);
        $this->assertStringContainsString('>= 5', $sql);
    }

    public function test_generates_scope_with_multiple_where_has(): void
    {
        $query = $this->queryWith([
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'has',
                ],
                [
                    'relationship' => 'tags',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'has',
                    'conditions' => [
                        ['column' => 'tags.name', 'operator' => '=', 'value' => 'featured', 'valueType' => 'hardcoded'],
                    ],
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->has('comments')", $scope);
        $this->assertStringContainsString("->whereHas('tags', function (\$q) {", $scope);
        $this->assertStringContainsString("\$q->where('tags.name', '=', 'featured')", $scope);
    }

    public function test_where_has_combined_with_regular_conditions(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'valueType' => 'hardcoded'],
            ],
            'whereHas' => [
                [
                    'relationship' => 'comments',
                    'sourceModel' => 'App\\Models\\Post',
                    'hasType' => 'has',
                    'conditions' => [
                        ['column' => 'comments.approved', 'operator' => '=', 'value' => '1', 'valueType' => 'hardcoded'],
                    ],
                ],
            ],
        ]);

        $scope = $this->generator->generateScope($query);

        $this->assertStringContainsString("->where('posts.status', '=', 'published')", $scope);
        $this->assertStringContainsString("->whereHas('comments', function (\$q) {", $scope);
    }

    // ─── PHPDoc generation ──────────────────────────────────────

    public function test_generates_scope_phpdoc_line_without_params(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'value' => 'published', 'parameter' => false],
            ],
        ]);

        $line = $this->generator->generateScopePhpDocLine($query);

        $this->assertEquals('@method static \\Illuminate\\Database\\Eloquent\\Builder testQuery()', $line);
    }

    public function test_generates_scope_phpdoc_line_with_parameterized_conditions(): void
    {
        $query = $this->queryWith([
            'conditions' => [
                ['column' => 'posts.status', 'operator' => '=', 'parameter' => true],
                ['column' => 'posts.category_id', 'operator' => '=', 'parameter' => true],
            ],
        ]);

        $line = $this->generator->generateScopePhpDocLine($query);

        $this->assertStringContainsString('testQuery(?string $status = null, ?string $categoryId = null)', $line);
    }

    public function test_generates_scope_phpdoc_line_uses_query_name_not_scope_prefix(): void
    {
        $query = $this->queryWith([
            'name' => 'scopeWhereHasActiveUsers',
        ]);

        $line = $this->generator->generateScopePhpDocLine($query);

        $this->assertStringContainsString('scopeWhereHasActiveUsers()', $line);
        $this->assertStringStartsWith('@method static \\Illuminate\\Database\\Eloquent\\Builder', $line);
    }

    // ─── Helpers ─────────────────────────────────────────────────

    /**
     * @param  array<string, mixed>  $overrides
     */
    private function queryWith(array $overrides): QueryDefinition
    {
        return QueryDefinition::fromArray(array_merge([
            'name' => 'testQuery',
            'baseTable' => 'posts',
            'baseModel' => 'App\\Models\\Post',
        ], $overrides));
    }
}
